# Generated by Django 4.1.4 on 2023-08-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compalints',
            new_name='Complaints',
        ),
    ]
