# Generated by Django 4.1.4 on 2023-07-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pcid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pcname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('orderid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('amount', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('netprice', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Compalint',
            fields=[
                ('compid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('compdesc', models.CharField(max_length=500)),
                ('compdt', models.DateField()),
                ('status', models.CharField(default='open', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
    ]
