# Generated by Django 4.1.4 on 2023-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_compalints_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='response',
            field=models.CharField(default='Response Awaited', max_length=400),
        ),
    ]
