# Generated by Django 4.1.4 on 2023-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_complaints_compdesc_alter_complaints_compdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='response',
            field=models.CharField(default='Response Awaited', max_length=400, null=True),
        ),
    ]
